# Generated by Django 5.2 on 2025-05-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_upload_cleaned_text_upload_llm_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='cleaned_text',
        ),
    ]
